### ISSUE TITLE
throws error regarding permissions but still works

### ISSUE THREAD

**Issue by oofdog** [cmehay/docker-tor-hidden-service#66]
Hi,
first of all, thank you very much for making this.
i am seeing in my logs that some kind of permissions error is being thrown but tor still manages to start up correctly. not sure what is going on. i'm using v3 so i'm loading my private key via the docker-compose secrets similar to this https://github.com/cmehay/docker-tor-hidden-service/blob/master/docker-compose.v3.yml the name of my key is `gm2`

```
tor2_1   | Entrypoint INFO     gm2: [redacted].onion:80
tor2_1   | Feb 17 03:20:57.854 [notice] Tor 0.4.4.7 (git-37a32b7ee76e5d52) running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1i, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
tor2_1   | Feb 17 03:20:57.854 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
tor2_1   | Feb 17 03:20:57.854 [notice] Read configuration file "/etc/tor/torrc".
tor2_1   | Feb 17 03:20:57.000 [notice] Parsing GEOIP IPv4 file /usr/local/share/tor/geoip.
tor2_1   | Feb 17 03:20:57.000 [notice] Parsing GEOIP IPv6 file /usr/local/share/tor/geoip6.
tor2_1   | Feb 17 03:20:58.000 [notice] Bootstrapped 0% (starting): Starting
tor2_1   | Feb 17 03:20:58.000 [notice] Starting with guard context "default"
tor2_1   | Entrypoint WARNING  ERROR:root:[Errno 13] Permission denied: '/run/secrets/gm2'
tor2_1   | Entrypoint WARNING  Traceback (most recent call last):
tor2_1   | Entrypoint WARNING    File "/usr/local/src/onions/onions/Service.py", line 128, in load_key_from_secrets
tor2_1   | Entrypoint WARNING      self._load_key(secret_file)
tor2_1   | Entrypoint WARNING    File "/usr/local/src/onions/onions/Service.py", line 113, in _load_key
tor2_1   | Entrypoint WARNING      with open(key_file, 'rb') as f:
tor2_1   | Entrypoint WARNING  PermissionError: [Errno 13] Permission denied: '/run/secrets/gm2'
tor2_1   | Entrypoint WARNING  WARNING:root:Fail to load key from secret, check the key or secret name collision
tor2_1   | Feb 17 03:20:59.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
tor2_1   | Feb 17 03:20:59.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
tor2_1   | Feb 17 03:20:59.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
tor2_1   | Feb 17 03:20:59.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
tor2_1   | Feb 17 03:20:59.000 [notice] Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection
tor2_1   | Feb 17 03:20:59.000 [notice] Bootstrapped 25% (requesting_status): Asking for networkstatus consensus
tor2_1   | Feb 17 03:20:59.000 [notice] Bootstrapped 30% (loading_status): Loading networkstatus consensus
tor2_1   | Feb 17 03:21:00.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
tor2_1   | Feb 17 03:21:01.000 [notice] Bootstrapped 40% (loading_keys): Loading authority key certs
tor2_1   | Feb 17 03:21:01.000 [notice] The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services.
tor2_1   | Feb 17 03:21:01.000 [notice] Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors
tor2_1   | Feb 17 03:21:01.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6834, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
tor2_1   | Feb 17 03:21:01.000 [notice] Bootstrapped 50% (loading_descriptors): Loading relay descriptors
tor2_1   | Feb 17 03:21:02.000 [notice] The current consensus contains exit nodes. Tor can build exit and internal paths.
tor2_1   | Feb 17 03:21:03.000 [notice] Bootstrapped 56% (loading_descriptors): Loading relay descriptors
tor2_1   | Feb 17 03:21:03.000 [notice] Bootstrapped 63% (loading_descriptors): Loading relay descriptors
tor2_1   | Feb 17 03:21:03.000 [notice] Bootstrapped 68% (loading_descriptors): Loading relay descriptors
tor2_1   | Feb 17 03:21:03.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
tor2_1   | Feb 17 03:21:04.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
tor2_1   | Feb 17 03:21:04.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
tor2_1   | Feb 17 03:21:04.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
tor2_1   | Feb 17 03:21:04.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
tor2_1   | Feb 17 03:21:04.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
tor2_1   | Feb 17 03:21:05.000 [notice] Bootstrapped 100% (done): Done
```

after that, tor works fine, so i'm not sure what's happening.
Thank you

**Comment by oofdog** [comment]
here's my docker compose

```
version: "3.7"
services:
  tor2:
    image: goldy/tor-hidden-service:0.4.4.7
    restart: always
    environment:
      GM2_TOR_SERVICE_HOSTS: 80:nginx:80
      GM2_TOR_SERVICE_VERSION: "3"
    volumes:
      - tor-keys:/var/lib/tor/hidden_service/
    secrets:
      - gm2
  nginx:
    ...

volumes:
  tor-keys:
    driver: local
secrets:
  gm2:
    file: ./private_key
```

**Comment by schildbach** [comment]
I've noticed this too.

**Comment by oofdog** [comment]
Just pulled the update, and it seems to work fine now. thank you.
